import  {PrismaClient} from '@prisma/client'

const prisma = new PrismaClient()

export default async function handler(req, res) {
  
    
    
      // Llamada a la API
      const equiposResponse = await fetch('https://socal-production.up.railway.app/equipos')
      const equipos = await equiposResponse.json()
    
      res.status(200).json(equipos)

}



// {
    // "id": "093822de-f0d1-43df-bf7d-1f85d12e9845",
    // "titulo": "Camioneta",
    // "descripcion": "(Surtidora de Combustible)",
    // "patente": "JXZJ-10",
    // "ano": "0",
    // "marca": "Maxus",
    // "modelo": "T-60",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Sergio Soto",
    // "imagen": "JXZJ.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "0b448f96-560a-4e27-8d76-d898ac797a10",
    // "titulo": "Camioneta",
    // "descripcion": "(jefe de obra) ",
    // "patente": "RWDX-87",
    // "ano": "0",
    // "marca": "Maxus",
    // "modelo": "T-60",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Manuel Carreño ",
    // "imagen": "RWDX.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "0fe2476b-d30e-4054-9e32-f0753c27a1bf",
    // "titulo": "Camión",
    // "descripcion": "0",
    // "patente": "RLRC-67",
    // "ano": "0",
    // "marca": "Foton ",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Sin Nombre",
    // "imagen": "RLRC.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "10ad88a6-c258-4603-b270-fe16caf86aa1",
    // "titulo": "Rodillo",
    // "descripcion": "0",
    // "patente": "WC12-81",
    // "ano": "0",
    // "marca": "Caterpillar",
    // "modelo": " CS 533E",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Enio Barrientos",
    // "imagen": "WC12.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "1900de67-fc57-49d2-b8bf-b803d687c16d",
    // "titulo": "Camioneta",
    // "descripcion": "(PAC) ",
    // "patente": "RGKC-95",
    // "ano": "0",
    // "marca": "Great Wall ",
    // "modelo": "POER ",
    // "motor": "00",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Emanuel Salgado  ",
    // "imagen": "RG KC.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "19d5d7c0-1b1e-4938-9a20-12a8628269fa",
    // "titulo": "Motoniveladora",
    // "descripcion": "0",
    // "patente": "FHZB-49",
    // "ano": "0",
    // "marca": "Caterpillar ",
    // "modelo": "140 m",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Max Montoya",
    // "imagen": "FHZB.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "22da8337-8097-4d37-929d-aff7b06fc940",
    // "titulo": "Camión",
    // "descripcion": "0",
    // "patente": "PJJG-58",
    // "ano": "0",
    // "marca": "Ford ",
    // "modelo": "Cargo",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Miguel Venegas",
    // "imagen": "PJJG.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "23540015-931d-4b68-8f10-5664ab628f98",
    // "titulo": "Tractor Desbrozador ",
    // "descripcion": "Agregar",
    // "patente": "KGCJ-98",
    // "ano": "0",
    // "marca": "John Deere ",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Mario Machuca ",
    // "imagen": "KGCJ.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "273295be-bc00-47ec-bcdb-33d3efa1aec4",
    // "titulo": "Camión ¾",
    // "descripcion": "0",
    // "patente": "PYZW-24",
    // "ano": "0",
    // "marca": "Chevrolet ",
    // "modelo": "NPR E5",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Víctor Chandía ",
    // "imagen": "PYZW.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "2d54bdb6-2833-47fb-a219-7a93a1903e00",
    // "titulo": "Camión Aljibe",
    // "descripcion": "0",
    // "patente": "BTCD-99",
    // "ano": "0",
    // "marca": "Volvo ",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Sin Nombre",
    // "imagen": "BTCD.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "3523dc29-0332-4c9b-bb60-85e680f061f3",
    // "titulo": "Camión",
    // "descripcion": "0",
    // "patente": "JXGK-20",
    // "ano": "0",
    // "marca": "Mercedes Benz ",
    // "modelo": "Axor",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Lizandro Sepúlveda",
    // "imagen": "JXGK.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "43754411-4665-4238-8370-13fb1b5a7266",
    // "titulo": "Retroexcavadora",
    // "descripcion": "0",
    // "patente": "BZRR-26",
    // "ano": "0",
    // "marca": "Caterpillar",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Danilo Godoy",
    // "imagen": "BZRR.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "48b9ab9d-e6f6-42fb-bee0-7403838ce13b",
    // "titulo": "Camión",
    // "descripcion": "0",
    // "patente": "HDTS-79",
    // "ano": "0",
    // "marca": "Volkswagen ",
    // "modelo": "Constellation",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Sergio Zambrano",
    // "imagen": "HDTS-79.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "4a8dff02-d441-433e-88ca-60c86a9df57a",
    // "titulo": "Camioneta",
    // "descripcion": "(Topografía) ",
    // "patente": "PRXF-41",
    // "ano": "0",
    // "marca": "Maxus",
    // "modelo": "T-60",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Carlos Mansilla ",
    // "imagen": "PRXF.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "4b9f4ccb-8fdc-43db-8cca-a7f483ead39d",
    // "titulo": "Cargador Frontal",
    // "descripcion": "0",
    // "patente": "0",
    // "ano": "0",
    // "marca": "Volvo",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Mario Velozo",
    // "imagen": "noposeevolvo.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "4f47362c-8cf3-44c0-bf3a-9f344df3eb9d",
    // "titulo": "Rodillo",
    // "descripcion": "0",
    // "patente": "PRSX-75",
    // "ano": "0",
    // "marca": "Hamm",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Sin Nombre",
    // "imagen": "PRSX.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "4f7a4a79-85b1-48f0-9a14-7de3ded40654",
    // "titulo": "Retroexcavadora",
    // "descripcion": "0",
    // "patente": "0",
    // "ano": "0",
    // "marca": "CASE 580 N",
    // "modelo": "CASE 580 N",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Eduardo Concha ",
    // "imagen": "noposeeretro.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "4fb70779-d790-4055-a291-7e1fb2b7581b",
    // "titulo": "Camión",
    // "descripcion": "0",
    // "patente": "KCFB-56",
    // "ano": "0",
    // "marca": "Volkswagen",
    // "modelo": "Constellation",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Alejandro Poveda",
    // "imagen": "KCFB.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "51363b2c-2096-4752-9be5-93e3bdfc473d",
    // "titulo": "Camioneta",
    // "descripcion": "(Residente) ",
    // "patente": "JRXB-40",
    // "ano": "0",
    // "marca": "SsanYong ",
    // "modelo": "Actyon Sport",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Daniel Gomez",
    // "imagen": "JRXB-40.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "5155b546-8a4f-4cd0-9dd1-6a0a3d22b15c",
    // "titulo": "Camión",
    // "descripcion": "0",
    // "patente": "LCVS-38",
    // "ano": "0",
    // "marca": "Mercedes Benz ",
    // "modelo": "Axor",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Ivan Orellana",
    // "imagen": "LCVS.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "547afa5b-c881-4a5c-ad96-5b1377d2611c",
    // "titulo": "Camión ¾",
    // "descripcion": "0",
    // "patente": "TB14-40",
    // "ano": "0",
    // "marca": "Kia Frontier ",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Carlos Rivera",
    // "imagen": "TB14.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "60da2103-a7e4-4adb-b4cd-36979e260223",
    // "titulo": "Camioneta",
    // "descripcion": "(Terreno) ",
    // "patente": "GBWW-25",
    // "ano": "0",
    // "marca": "Nissan ",
    // "modelo": "terrano",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Gabriel Besil",
    // "imagen": "GBWW.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "621ca319-20bd-48b6-9598-d1d7cd8f9986",
    // "titulo": "Camioneta",
    // "descripcion": "(Residente)",
    // "patente": "KWBB-21",
    // "ano": "0",
    // "marca": "Ford Ranger",
    // "modelo": " XLT 3.2",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Tito Añazco",
    // "imagen": "KW BB.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "6526cace-e68c-46ae-a35e-f968cc86b6a4",
    // "titulo": "Camión Tolva",
    // "descripcion": "0",
    // "patente": "GZHB-41",
    // "ano": "0",
    // "marca": "Ford",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Sin Nombre",
    // "imagen": "GZHB.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "709e41ed-3c51-46b5-a4e6-b75a30323615",
    // "titulo": "Camioneta",
    // "descripcion": "(Laboratorista) ",
    // "patente": "HKZF-28",
    // "ano": "0",
    // "marca": "Chevrolet ",
    // "modelo": "dmax",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "00",
    // "operador": "Miguel Jaramillo",
    // "imagen": "HKZF.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "7d512511-c84c-4434-8a4d-301ed0eb1c14",
    // "titulo": "Camión",
    // "descripcion": "0",
    // "patente": "RDXX-13",
    // "ano": "0",
    // "marca": "Foton ",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Sin Nombre",
    // "imagen": "RDXX.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "80650b3e-a690-4b88-93fe-9d6432253a44",
    // "titulo": "Camioneta",
    // "descripcion": "(Vigilancia Vial) ",
    // "patente": "PSTX-63",
    // "ano": "0",
    // "marca": "Ford Ranger ",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Jaime Valenzuela ",
    // "imagen": "PSTX.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "8adc7691-d14e-44d7-b2b6-96c5d552ca61",
    // "titulo": "Camioneta",
    // "descripcion": "(topografo)",
    // "patente": "ZS66-11",
    // "ano": "0",
    // "marca": "Chevrolet ",
    // "modelo": "dmax",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Roberto Bravo",
    // "imagen": "ZS66.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "8c663699-99b9-44f9-a223-651bdb8c80f2",
    // "titulo": "Camioneta",
    // "descripcion": "0",
    // "patente": "JYPD-25",
    // "ano": "0",
    // "marca": "Maxus",
    // "modelo": "T-60",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Mario Velozo",
    // "imagen": "JYPD.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "953d87dc-d5af-494b-81da-35103f72b7e6",
    // "titulo": "Camioneta",
    // "descripcion": "0",
    // "patente": "FZSK-89",
    // "ano": "0",
    // "marca": "SsangYong ",
    // "modelo": "Actyon Sport",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Sin Chofer",
    // "imagen": "FZSK.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "9aba33d4-b322-41eb-8beb-d5fe4f099fa2",
    // "titulo": "Tractor Desbrozador",
    // "descripcion": "(Terreno) ",
    // "patente": "GCSC-63",
    // "ano": "0",
    // "marca": "New Holland",
    // "modelo": " 6020",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Jony Jara",
    // "imagen": "GCSC.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "a6a33b83-719b-4a4f-9fa9-f50605547dc3",
    // "titulo": "Camión ¾ ",
    // "descripcion": "0",
    // "patente": "PZKG-53",
    // "ano": "0",
    // "marca": "Chevrolet ",
    // "modelo": "NPR E5",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Esteban Carrillo",
    // "imagen": "PZKG.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "bdeef785-8b4f-4250-b1cb-4ea769687b0e",
    // "titulo": "Excavadora",
    // "descripcion": "0",
    // "patente": "DDHW-46",
    // "ano": "0",
    // "marca": "Kobelco ",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Sin Nombre",
    // "imagen": "DDHW.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "c3c8a7d4-e7ba-422b-8592-57df7c575763",
    // "titulo": "Camión Tolva ",
    // "descripcion": "0",
    // "patente": "ZS10-22",
    // "ano": "0",
    // "marca": "Mercedes Benz ",
    // "modelo": "1520",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Heriberto Pacheco",
    // "imagen": "ZS10.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "c9d92e81-ff62-4d6e-96b5-38469b6962a6",
    // "titulo": "Camioneta",
    // "descripcion": "(Prevención de Riesgos) ",
    // "patente": "JFFZ-57",
    // "ano": "0",
    // "marca": "Mitsubishi",
    // "modelo": "L-200",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Sergio Lincoqueo",
    // "imagen": "JFFZ.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "cb3993f5-01c8-42d0-9fa8-072e937d0339",
    // "titulo": "Motoniveladora",
    // "descripcion": "0",
    // "patente": "0",
    // "ano": "0",
    // "marca": "Volvo",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Adrián Jara",
    // "imagen": "noposeevolvo.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "d31fb4ba-6216-4794-ae05-e449e6d506a3",
    // "titulo": "Motoniveladora",
    // "descripcion": "0",
    // "patente": "DSVB-24",
    // "ano": "0",
    // "marca": "Caterpillar ",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Sin Nombre",
    // "imagen": "DSVB.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "d3f92182-ffa0-4848-ae38-5f543564f237",
    // "titulo": "Retroexcavadora",
    // "descripcion": "0",
    // "patente": "0",
    // "ano": "2022",
    // "marca": "Hyundai",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Víctor Pineda",
    // "imagen": "noposee.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "d43ea113-cc37-43e7-b47e-220dc97167fa",
    // "titulo": "Camioneta",
    // "descripcion": "(prevención de riesgo) ",
    // "patente": "HFRL-67 ",
    // "ano": "0",
    // "marca": "SsanYong ",
    // "modelo": "Actyon Sport",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Gladys Delgado  ",
    // "imagen": "HFRL.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "d93aee12-0923-4c4c-b24c-9311045e2818",
    // "titulo": "Camioneta",
    // "descripcion": "(Nivel de Servicio) ",
    // "patente": "SGZT-44",
    // "ano": "0",
    // "marca": "Ford Ranger",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Gerardo Paillaqueo",
    // "imagen": "SGZT.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "de788521-7e92-439d-b57e-25bc1bb3c1e7",
    // "titulo": "Motoniveladora",
    // "descripcion": "0",
    // "patente": "CLJR-69",
    // "ano": "0",
    // "marca": " New Holland  ",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Sin Nombre",
    // "imagen": "CLJR.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "e5000fa5-e6c4-41eb-a6a2-9a3ddc816e01",
    // "titulo": "Cargador Frontal",
    // "descripcion": "0",
    // "patente": "0",
    // "ano": "0",
    // "marca": "New Holland",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Ignacio Lobos",
    // "imagen": "ignaciologos.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "e78269ba-5689-4ab7-89ba-1e9c1cd16ac2",
    // "titulo": "Motoniveladora",
    // "descripcion": "0",
    // "patente": "PSPH-13",
    // "ano": "0",
    // "marca": "New Holland",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Jorge Ramos",
    // "imagen": "PSPH.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "f3b2a2c9-cb84-402c-8c0d-271c3af2a0ba",
    // "titulo": "Camión",
    // "descripcion": "0",
    // "patente": "RPXB-93",
    // "ano": "0",
    // "marca": "Maxus ",
    // "modelo": "0",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Sin Nombre",
    // "imagen": "RPXB.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "f4f81e8f-71a6-4103-a1a0-0c9ae15e2d7a",
    // "titulo": "Camioneta",
    // "descripcion": "(vigilancia vial)",
    // "patente": "RRJV-50",
    // "ano": "0",
    // "marca": "Maxus",
    // "modelo": "T-60",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "0",
    // "operador": "Brayan Llanquiman",
    // "imagen": "RRJV.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467f1",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "GSSP-84-K",
    // "ano": "2014",
    // "marca": "FREIGHTLINER",
    // "modelo": "M2 106",
    // "motor": "926928C0997126",
    // "serie": "3ALHCYDJ2DDFH5891",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "RAFAEL ESPARZA",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467f2",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "BZCT-15-K",
    // "ano": "2009",
    // "marca": "FREIGHTLINER",
    // "modelo": "M2 106",
    // "motor": "90698000738108",
    // "serie": "1FVHCYCSX9HAD5863",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 13,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467f3",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "GZHB-41-6",
    // "ano": "2015",
    // "marca": "FORD",
    // "modelo": "CARGO  3133",
    // "motor": "36470055",
    // "serie": "9BFZEB4J3EBS62278",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "VICTOR FLORES",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467f4",
    // "titulo": "CAMION 3/4",
    // "descripcion": "AGREGAR",
    // "patente": "RLRC-92",
    // "ano": "2022",
    // "marca": "FOTON",
    // "modelo": "AUMARK 613E",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "SCOTIABANK ",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467f5",
    // "titulo": "CAMION 3/4",
    // "descripcion": "AGREGAR",
    // "patente": "RLRC-67",
    // "ano": "2022",
    // "marca": "FOTON",
    // "modelo": "AUMARK 613E",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "SCOTIABANK ",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467f6",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "JGPJ-58",
    // "ano": "2017",
    // "marca": "FORD",
    // "modelo": "3133",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "BEKA",
    // "operador": "MIGUEL VENEGAS",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467f7",
    // "titulo": "CAMION MIXER",
    // "descripcion": "AGREGAR",
    // "patente": "NL-2704-2",
    // "ano": "1996",
    // "marca": "MERCEDES BENZ",
    // "modelo": "3234B- 8X4",
    // "motor": "441988-10-833991",
    // "serie": "WDB-6251151K140463",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 13,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467f8",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "LPDL-79",
    // "ano": "2019",
    // "marca": "VOLKSWAGEN",
    // "modelo": "DELIVERY 9170",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "PENTA SECURYTI",
    // "operador": "MARCELO GANGAS",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467f9",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "FHSH-38",
    // "ano": "2013",
    // "marca": "VOLKSWAGEN",
    // "modelo": "CONSTELLACION 31,280",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "DANIELA ALBORNOZ",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467h1",
    // "titulo": "CAMION SLURRY",
    // "descripcion": "AGREGAR",
    // "patente": "HYHW-19-0",
    // "ano": "2006",
    // "marca": "STERLINE",
    // "modelo": "L 7500 (SLURRY)",
    // "motor": "9DG04788",
    // "serie": "2FZHATDA36AV67999",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 13,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467h2",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "HDTS-79-1",
    // "ano": "2014",
    // "marca": "VOLKSWAGEN",
    // "modelo": "CONSTELLACION 31,390",
    // "motor": "36385825",
    // "serie": "9536T8265DR248663",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "SEGIO ZAMBRANO",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467h3",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "HDTS-80-5",
    // "ano": "2014",
    // "marca": "VOLKSWAGEN",
    // "modelo": "CONSTELLACION 31,390",
    // "motor": "36385822",
    // "serie": "9536T8268DR251086",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "MAURICIO COLIQUEO",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467h4",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "KCFB-56-2",
    // "ano": "2018",
    // "marca": "VOLKSWAGEN",
    // "modelo": "CONSTELLACION 31,330",
    // "motor": "36577698",
    // "serie": "9536Y8264JR816463",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "ALEJANDRO POVEDA",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467h5",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "DKDF-93-K",
    // "ano": "2012",
    // "marca": "VOLVO",
    // "modelo": "FM X",
    // "motor": "D13842693A1E",
    // "serie": "93KJS02D5BE774310",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "NELSON AEDO",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467h6",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "JXGK-19-7",
    // "ano": "2018",
    // "marca": "MERCEDES BENZ",
    // "modelo": "AXOR 3131 K",
    // "motor": "926992U119366",
    // "serie": "9BM958260HB050182",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "IGNACIO ANGULO",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467h7",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "JXGK-20-0",
    // "ano": "2018",
    // "marca": "MERCEDES BENZ",
    // "modelo": "AXOR 3131 K",
    // "motor": "926992U11862238",
    // "serie": "9BM958260HB43585",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "LIZANDO SEPULVEDA",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467h8",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "LCVS-40-8",
    // "ano": "2019",
    // "marca": "MERCEDES BENZ",
    // "modelo": "AXOR 3131 K",
    // "motor": "926992U1252806",
    // "serie": "9BM958260KB114611",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "GERMAN ANGULO",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467h9",
    // "titulo": "CAMION PLUMA",
    // "descripcion": "AGREGAR",
    // "patente": "YF95-63-7",
    // "ano": "2006",
    // "marca": "MERCEDES BENZ",
    // "modelo": "1718 M 48",
    // "motor": "904938576723",
    // "serie": "9BM6931864B355142",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467i1",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "ZS10-22",
    // "ano": "2006",
    // "marca": "MERCEDES BENZ",
    // "modelo": "15200 48",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ESTEBAN ALBORNOZ",
    // "operador": "HERIBERTO PACHECO",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467i2",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "ZN-9304-6",
    // "ano": "2006",
    // "marca": "MERCEDES BENZ",
    // "modelo": "2428",
    // "motor": "906953637186",
    // "serie": "9BM6933485B429109",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "VICTOR FLORES",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467i3",
    // "titulo": "CAMION IMPRIMADOR",
    // "descripcion": "AGREGAR",
    // "patente": "HFPL-25-3",
    // "ano": "2015",
    // "marca": "FREIGHTLINER",
    // "modelo": "M2 106",
    // "motor": "902919C1078435",
    // "serie": "3ALACYCS2FDGS3344",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 5,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467i4",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "DYKF-84-8",
    // "ano": "2012",
    // "marca": "FREIGHTLINER",
    // "modelo": "M2 106",
    // "motor": "92692800947767",
    // "serie": "1FVHCYDJXDHBY4454",
    // "propietario": "SANTIAGO ALBORNOZ",
    // "operador": "ATILIO ROGEL",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 9,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467i5",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "FSDH-23",
    // "ano": "2013",
    // "marca": "FREIGHTLINER",
    // "modelo": "CL120",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "SANTIAGO ALBORNOZ",
    // "operador": "OSCAR VEGA",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467i6",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "RZHP-38",
    // "ano": "2022",
    // "marca": "FREIGHTLINER",
    // "modelo": "CA116",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "BANCO CHILE",
    // "operador": "ESTEBAN ALBORNOZ",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467i7",
    // "titulo": "CAMION",
    // "descripcion": "AGREGAR",
    // "patente": "RCGD-34",
    // "ano": "2021",
    // "marca": "MERCEDEZ BENZ",
    // "modelo": "NEW ACTROS 2645",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "SANTIAGO ALBORNOZ",
    // "operador": "RODRIGO DAZA",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467i8",
    // "titulo": "BULLDOZER",
    // "descripcion": "AGREGAR",
    // "patente": "0",
    // "ano": "1992",
    // "marca": "CATTERPILAR",
    // "modelo": "D4CPG",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467i9",
    // "titulo": "BULLDOZER",
    // "descripcion": "AGREGAR",
    // "patente": "0",
    // "ano": "1996",
    // "marca": "DRESSER",
    // "modelo": "TD-15E",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 13,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467j1",
    // "titulo": "CARGADOR",
    // "descripcion": "AGREGAR",
    // "patente": "0",
    // "ano": "1982",
    // "marca": "CATTERPILAR",
    // "modelo": "930T",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 13,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467j2",
    // "titulo": "CARGADOR",
    // "descripcion": "AGREGAR",
    // "patente": "FPWW-75",
    // "ano": "0",
    // "marca": "NEW HOLLAND",
    // "modelo": "W 190 C",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467j3",
    // "titulo": "CARGADOR",
    // "descripcion": "AGREGAR",
    // "patente": "ZJ23-62",
    // "ano": "2006",
    // "marca": "VOLVO",
    // "modelo": "L 60 E",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467j4",
    // "titulo": "EXCAVADORA",
    // "descripcion": "AGREGAR",
    // "patente": "WE68-04",
    // "ano": "2006",
    // "marca": "JOHN DEERE",
    // "modelo": "200 C LC",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 13,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467j5",
    // "titulo": "EXCAVADORA",
    // "descripcion": "AGREGAR",
    // "patente": "BTVS-33",
    // "ano": "2009",
    // "marca": "KOBELCO",
    // "modelo": "SK 210 LC",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467j6",
    // "titulo": "EXCAVADORA",
    // "descripcion": "AGREGAR",
    // "patente": "DVCR-25",
    // "ano": "2012",
    // "marca": "KOBELCO",
    // "modelo": "SK 210 LC",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 13,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467j7",
    // "titulo": "EXCAVADORA",
    // "descripcion": "AGREGAR",
    // "patente": "FTHR-84",
    // "ano": "2013",
    // "marca": "KOBELCO",
    // "modelo": "SK 210 LC",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467j8",
    // "titulo": "EXCAVADORA",
    // "descripcion": "AGREGAR",
    // "patente": "DDHW-46",
    // "ano": "2011",
    // "marca": "KOBELCO",
    // "modelo": "SK 210 LC",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 13,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467j9",
    // "titulo": "GRAVILLADORA",
    // "descripcion": "AGREGAR",
    // "patente": "XX60-47",
    // "ano": "1995",
    // "marca": "ROSSCO FLAHEIY",
    // "modelo": "SPRH H",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467k1",
    // "titulo": "BARREDORA",
    // "descripcion": "AGREGAR",
    // "patente": "HCDC-12",
    // "ano": "2011",
    // "marca": "LAYMOR",
    // "modelo": "8 HC",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 5,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467k2",
    // "titulo": "BARREDORA",
    // "descripcion": "AGREGAR",
    // "patente": "LXBJ-91",
    // "ano": "2013",
    // "marca": "LAYMOR",
    // "modelo": "8 HC",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 13,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467k3",
    // "titulo": "MOTONIVELADORA",
    // "descripcion": "AGREGAR",
    // "patente": "VG20-93",
    // "ano": "2003",
    // "marca": "CATTERPILAR",
    // "modelo": "160 H",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "JAVIER ZAMBRANO",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 10,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467k4",
    // "titulo": "MOTONIVELADORA",
    // "descripcion": "AGREGAR",
    // "patente": "DSVB-24",
    // "ano": "2012",
    // "marca": "CATTERPILAR",
    // "modelo": "140 K",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467k5",
    // "titulo": "MOTONIVELADORA",
    // "descripcion": "AGREGAR",
    // "patente": "WU54-88",
    // "ano": "2006",
    // "marca": "NEW HOLLAND",
    // "modelo": "RG200B",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 13,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467k6",
    // "titulo": "MOTONIVELADORA",
    // "descripcion": "AGREGAR",
    // "patente": "GZYD-87",
    // "ano": "2015",
    // "marca": "NEW HOLLAND",
    // "modelo": "RG200B",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "BANCO SANTANDER",
    // "operador": "DIEGO TORRES",
    // "imagen": "GZYD.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 6,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467k7",
    // "titulo": "MOTONIVELADORA",
    // "descripcion": "AGREGAR",
    // "patente": "CLJR-69",
    // "ano": "2010",
    // "marca": "NEW HOLLAND",
    // "modelo": "RG200B",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "ELIAS FUENTES",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467k8",
    // "titulo": "MOTONIVELADORA",
    // "descripcion": "AGREGAR",
    // "patente": "WV58-02",
    // "ano": "2007",
    // "marca": "JOHN DEERE",
    // "modelo": "770 D",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 5,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467k9",
    // "titulo": "RETROEXCAVADORA",
    // "descripcion": "AGREGAR",
    // "patente": "SGZZ-67",
    // "ano": "1998",
    // "marca": "CATTERPILAR",
    // "modelo": "416-C",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467m1",
    // "titulo": "RETROEXCAVADORA",
    // "descripcion": "AGREGAR",
    // "patente": "HYVJ-76-0",
    // "ano": "2016",
    // "marca": "CASE",
    // "modelo": "580N 4WD",
    // "motor": "6136517",
    // "serie": "HBZN580NEFAH14692",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "ZAM/RFA/BFL",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 10,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467m2",
    // "titulo": "RETROEXCAVADORA",
    // "descripcion": "AGREGAR",
    // "patente": "LPYH-73",
    // "ano": "2019",
    // "marca": "CASE",
    // "modelo": "580N",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "PENTA FINANCIERO",
    // "operador": "CRISTOPHER CONCHA",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467m3",
    // "titulo": "RETROEXCAVADORA",
    // "descripcion": "AGREGAR",
    // "patente": "LWTW-59",
    // "ano": "2020",
    // "marca": "CASE",
    // "modelo": "580N",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "PENTA FINANCIERO",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 8,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467m4",
    // "titulo": "RETROEXCAVADORA",
    // "descripcion": "AGREGAR",
    // "patente": "RFHB-80",
    // "ano": "2021",
    // "marca": "JOHN DEERE",
    // "modelo": "310 L",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "SCOTIABANL",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 12,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467m6",
    // "titulo": "RODILLO",
    // "descripcion": "AGREGAR",
    // "patente": "NY22-00",
    // "ano": "1996",
    // "marca": "SD-100-D",
    // "modelo": "INGERSOLL",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "0",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 4,
    // "FK_Usuario": 1
    // },
    // {
    // "id": "fa801c12-6ed3-4d05-af3e-4effdb5467m7",
    // "titulo": "TRACTOR",
    // "descripcion": "AGREGAR",
    // "patente": "KG CJ 98",
    // "ano": "2018",
    // "marca": "JHON DEERE",
    // "modelo": "5090 E",
    // "motor": "0",
    // "serie": "0",
    // "propietario": "ARIDOS SOCAL LTDA",
    // "operador": "CAUTIN",
    // "imagen": "camion.jpg",
    // "FK_Categoria": 10,
    // "FK_Faena": 14,
    // "FK_Usuario": 1
    // }